Several minor changes

diff --git a/libpqxx/configure b/libpqxx/configure
--- a/libpqxx/configure
+++ b/libpqxx/configure
@@ -9416,6 +9416,70 @@ else
 fi
 
 
+echo "$as_me:$LINENO: checking PQfreemem()" >&5
+echo $ECHO_N "checking PQfreemem()... $ECHO_C" >&6
+
+
+pqfreemem=yes
+echo "$as_me:$LINENO: checking whether PQfreemem is declared" >&5
+echo $ECHO_N "checking whether PQfreemem is declared... $ECHO_C" >&6
+if test "${ac_cv_have_decl_PQfreemem+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <${with_postgres_include}/libpq-fe.h>
+
+int
+main ()
+{
+#ifndef PQfreemem
+  char *p = (char *) PQfreemem;
+#endif
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_have_decl_PQfreemem=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_have_decl_PQfreemem=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $ac_cv_have_decl_PQfreemem" >&5
+echo "${ECHO_T}$ac_cv_have_decl_PQfreemem" >&6
+if test $ac_cv_have_decl_PQfreemem = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_PQFREEMEM 1
+_ACEOF
+
+else
+  pqfreemem=no
+fi
+
+
 ac_ext=cc
 ac_cpp='$CXXCPP $CPPFLAGS'
 ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
