MinGW Makefile, thanks Pasquale Fersini

diff --git a/libpqxx/configure b/libpqxx/configure
--- a/libpqxx/configure
+++ b/libpqxx/configure
@@ -466,7 +466,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot PQXXVERSION CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CC CFLAGS ac_ct_CC CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE build build_cpu build_vendor build_os host host_cpu host_vendor host_os EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL MKDIR DOXYGEN BUILD_REFERENCE_TRUE BUILD_REFERENCE_FALSE XMLTO BUILD_TUTORIAL_TRUE BUILD_TUTORIAL_FALSE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT with_postgres_lib with_postgres_include POSTGRES_LIB POSTGRES_INCLUDE LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot PQXXVERSION CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CC CFLAGS ac_ct_CC CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE build build_cpu build_vendor build_os host host_cpu host_vendor host_os EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL MKDIR DOXYGEN BUILD_REFERENCE_TRUE BUILD_REFERENCE_FALSE XMLTO BUILD_TUTORIAL_TRUE BUILD_TUTORIAL_FALSE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT PG_CONFIG with_postgres_lib with_postgres_include POSTGRES_LIB POSTGRES_INCLUDE LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1052,13 +1052,6 @@ Optional Packages:
                           both]
   --with-tags[=TAGS]
                           include additional configurations [automatic]
-  --with-postgres-include PostgreSQL headers directory
-
-  --with-postgres-lib     PostgreSQL library directory containing libpq
-
-  --with-postgres         PostgreSQL common directory. Use this to specify
-                          libs & includes rooted at one place
-
 
 Some influential environment variables:
   CXX         C++ compiler command
@@ -4176,7 +4169,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4179 "configure"' > conftest.$ac_ext
+  echo '#line 4172 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -5280,7 +5273,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:5283:" \
+echo "$as_me:5276:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -6312,11 +6305,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6315: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6308: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6319: \$? = $ac_status" >&5
+   echo "$as_me:6312: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -6545,11 +6538,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6548: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6541: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6552: \$? = $ac_status" >&5
+   echo "$as_me:6545: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -6612,11 +6605,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6615: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6608: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:6619: \$? = $ac_status" >&5
+   echo "$as_me:6612: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -8787,7 +8780,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 8790 "configure"
+#line 8783 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -8885,7 +8878,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 8888 "configure"
+#line 8881 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11062,11 +11055,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11065: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11058: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:11069: \$? = $ac_status" >&5
+   echo "$as_me:11062: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -11129,11 +11122,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11132: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11125: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:11136: \$? = $ac_status" >&5
+   echo "$as_me:11129: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -12483,7 +12476,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12486 "configure"
+#line 12479 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12581,7 +12574,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12584 "configure"
+#line 12577 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13408,11 +13401,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13411: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13404: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13415: \$? = $ac_status" >&5
+   echo "$as_me:13408: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -13475,11 +13468,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13478: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13471: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13482: \$? = $ac_status" >&5
+   echo "$as_me:13475: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -15507,11 +15500,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15510: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15503: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15514: \$? = $ac_status" >&5
+   echo "$as_me:15507: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -15740,11 +15733,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15743: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15736: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15747: \$? = $ac_status" >&5
+   echo "$as_me:15740: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -15807,11 +15800,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15810: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15803: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:15814: \$? = $ac_status" >&5
+   echo "$as_me:15807: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -17982,7 +17975,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 17985 "configure"
+#line 17978 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -18080,7 +18073,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 18083 "configure"
+#line 18076 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -19857,123 +19850,62 @@ ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $
 ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
-# Where are the postgres includes...
-postgres_include_default=
-for usual_suspect in \
-	/usr/local/include/postgresql \
-	/usr/local/include/pgsql \
-	/usr/local/pgsql/include \
-	/usr/local/include \
-	/usr/include/postgresql \
-	/usr/include/pgsql \
-	/usr/include \
-	/opt/postgresql/include \
-	/opt/pgsql/include \
-; do
-as_ac_File=`echo "ac_cv_file_$usual_suspect/libpq-fe.h" | $as_tr_sh`
-echo "$as_me:$LINENO: checking for $usual_suspect/libpq-fe.h" >&5
-echo $ECHO_N "checking for $usual_suspect/libpq-fe.h... $ECHO_C" >&6
-if eval "test \"\${$as_ac_File+set}\" = set"; then
+# Find PostgreSQL includes and libraries
+for ac_prog in pg_config
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_PG_CONFIG+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-  test "$cross_compiling" = yes &&
-  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
-echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
-   { (exit 1); exit 1; }; }
-if test -r "$usual_suspect/libpq-fe.h"; then
-  eval "$as_ac_File=yes"
-else
-  eval "$as_ac_File=no"
-fi
-fi
-echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_File'}'`" >&5
-echo "${ECHO_T}`eval echo '${'$as_ac_File'}'`" >&6
-if test `eval echo '${'$as_ac_File'}'` = yes; then
-  postgres_include_default=$usual_suspect
-fi
-
-	if test -n "$postgres_include_default" ; then
-		break
-	fi
+  case $PG_CONFIG in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_PG_CONFIG="$PG_CONFIG" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_PG_CONFIG="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
 done
 
-
-# Check whether --with-postgres-include or --without-postgres-include was given.
-if test "${with_postgres_include+set}" = set; then
-  withval="$with_postgres_include"
-  test "$withval" = no || with_postgres_include=$withval
-
-else
-  with_postgres_include=$postgres_include_default
-
-fi;
-
-# ..and libraries?
-postgres_lib_default=
-for usual_suspect in \
-	/usr/local/lib/postgresql \
-	/usr/local/lib/pgsql \
-	/usr/local/pgsql/lib \
-	/usr/local/lib \
-	/usr/lib/postgresql \
-	/usr/lib/pgsql \
-	/usr/lib \
-	/opt/postgresql/lib \
-	/opt/pgsql/lib \
-; do
-	for library_extension in so a sa ; do
-as_ac_File=`echo "ac_cv_file_$usual_suspect/libpq.$library_extension" | $as_tr_sh`
-echo "$as_me:$LINENO: checking for $usual_suspect/libpq.$library_extension" >&5
-echo $ECHO_N "checking for $usual_suspect/libpq.$library_extension... $ECHO_C" >&6
-if eval "test \"\${$as_ac_File+set}\" = set"; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  test "$cross_compiling" = yes &&
-  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
-echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
-   { (exit 1); exit 1; }; }
-if test -r "$usual_suspect/libpq.$library_extension"; then
-  eval "$as_ac_File=yes"
-else
-  eval "$as_ac_File=no"
+  ;;
+esac
 fi
-fi
-echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_File'}'`" >&5
-echo "${ECHO_T}`eval echo '${'$as_ac_File'}'`" >&6
-if test `eval echo '${'$as_ac_File'}'` = yes; then
-  postgres_lib_default=$usual_suspect
+PG_CONFIG=$ac_cv_path_PG_CONFIG
+
+if test -n "$PG_CONFIG"; then
+  echo "$as_me:$LINENO: result: $PG_CONFIG" >&5
+echo "${ECHO_T}$PG_CONFIG" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
 fi
 
-	done
-	if test -n "$postgres_lib_default" ; then
-		break
-	fi
+  test -n "$PG_CONFIG" && break
 done
 
-
-# Check whether --with-postgres-lib or --without-postgres-lib was given.
-if test "${with_postgres_lib+set}" = set; then
-  withval="$with_postgres_lib"
-  test "$withval" = no || with_postgres_lib=$withval
-
-else
-  with_postgres_lib=$postgres_lib_default
-
-fi;
-
-# provide one way to specify both include and lib
-
-# Check whether --with-postgres or --without-postgres was given.
-if test "${with_postgres+set}" = set; then
-  withval="$with_postgres"
-  test "$withval" = no || with_postgres=$withval
-		with_postgres_lib=${with_postgres}/lib
-		with_postgres_include=${with_postgres}/include
-
-else
-  with_postgres=no
-
-fi;
+if test -z "$PG_CONFIG" || test ! -r "$PG_CONFIG"; then
+	{ { echo "$as_me:$LINENO: error: PostgreSQL configuration script was not found" >&5
+echo "$as_me: error: PostgreSQL configuration script was not found" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+with_postgres_include=`$PG_CONFIG --includedir`
+{ echo "$as_me:$LINENO: using PostgreSQL headers at $with_postgres_include" >&5
+echo "$as_me: using PostgreSQL headers at $with_postgres_include" >&6;}
+with_postgres_lib=`$PG_CONFIG --libdir`
+{ echo "$as_me:$LINENO: using PostgreSQL libraries at $with_postgres_lib" >&5
+echo "$as_me: using PostgreSQL libraries at $with_postgres_lib" >&6;}
 
 
 
@@ -20058,12 +19990,10 @@ else
   { { echo "$as_me:$LINENO: error: Failed to find a suitable libpq.
 
 PostgreSQL's libpq needs to be installed.
-Perhaps you need to specify --with-postgres-lib?
 " >&5
 echo "$as_me: error: Failed to find a suitable libpq.
 
 PostgreSQL's libpq needs to be installed.
-Perhaps you need to specify --with-postgres-lib?
 " >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -20376,12 +20306,8 @@ if test `eval echo '${'$as_ac_Header'}'` = yes; then
   :
 else
   { { echo "$as_me:$LINENO: error: Can't find libpq-fe.h in ${with_postgres_include}.
-Please specify the location of the PostgreSQL include files with
---with-postgres-include=... or --with-postgres=...
 " >&5
 echo "$as_me: error: Can't find libpq-fe.h in ${with_postgres_include}.
-Please specify the location of the PostgreSQL include files with
---with-postgres-include=... or --with-postgres=...
 " >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -22531,6 +22457,7 @@ s,@BUILD_TUTORIAL_FALSE@,$BUILD_TUTORIAL_FALSE,;t t
 s,@MAINTAINER_MODE_TRUE@,$MAINTAINER_MODE_TRUE,;t t
 s,@MAINTAINER_MODE_FALSE@,$MAINTAINER_MODE_FALSE,;t t
 s,@MAINT@,$MAINT,;t t
+s,@PG_CONFIG@,$PG_CONFIG,;t t
 s,@with_postgres_lib@,$with_postgres_lib,;t t
 s,@with_postgres_include@,$with_postgres_include,;t t
 s,@POSTGRES_LIB@,$POSTGRES_LIB,;t t
