Checks for abs(long); other Sun fixes

diff --git a/trunk/libpqxx/configure b/trunk/libpqxx/configure
--- a/trunk/libpqxx/configure
+++ b/trunk/libpqxx/configure
@@ -9699,6 +9699,53 @@ rm -f conftest.$ac_objext conftest.$ac_ext
 echo "$as_me:$LINENO: result: $it" >&5
 echo "${ECHO_T}$it" >&6
 
+# See if abs() works on a long int
+echo "$as_me:$LINENO: checking for abs(long int)" >&5
+echo $ECHO_N "checking for abs(long int)... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <cstdlib>
+int
+main ()
+{
+using namespace std;long a=-2000000000; long b=abs(a);
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_ABS_LONG 1
+_ACEOF
+
+	 abslong='yes'
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+abslong='no'
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+echo "$as_me:$LINENO: result: $abslong" >&5
+echo "${ECHO_T}$abslong" >&6
+
 ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
 ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
