*** empty log message ***

diff --git a/trunk/libpqxx/selftest b/trunk/libpqxx/selftest
--- a/trunk/libpqxx/selftest
+++ b/trunk/libpqxx/selftest
@@ -1,5 +1,8 @@
 #! /bin/sh
 
+# Exit immediately if any command fails
+set -e
+
 echo "Cleaning up any garbage from previous failed test runs"
 psql $DBNAME -c "DELETE FROM events WHERE year=1977"
 echo
