Use `uv` instead of `virtualenv` & `pip`. (#1031)
Speeds up the `lint` and `format` scripts.  I could probably get a bit more speed with a bit more work, but they're no longer annoying.

diff --git a/tools/lint b/tools/lint
--- a/tools/lint
+++ b/tools/lint
@@ -2,6 +2,8 @@
 #
 # Routine sanity checks for libpqxx source tree.
 #
+# This script requires "uv" to be installed.
+#
 # Optionally, set environment variable "srcdir" to the source directory.  It
 # defaults to the parent directory of the one where this script is.  This trick
 # requires bash (or a close equivalent) as the shell.
@@ -14,40 +16,12 @@ PQXXVERSION="$(cd "$SRCDIR" && "$SRCDIR/tools/extract_version")"
 ARGS="${1:-}"
 
 
-set_up() {
-    MY_VENV="$(mktemp -d)"
-    if [ -z "$MY_VENV" ]
-    then
-        echo "Failed to set up virtualenv." >&2
-        exit 2
-    fi
-    virtualenv -q "$MY_VENV"
-    # shellcheck disable=SC1091
-    . "$MY_VENV/bin/activate"
-    pip install -q pyflakes ruff shellcheck-py
-}
-
-
-clean_up() {
-    if [ -n "${MY_VENV:-}" ] && [ "${VIRTUAL_ENV:-x}" = "${MY_VENV:-y}" ]
-    then
-        deactivate || true
-    fi
-    if [ -n "${MY_VENV:-}" ] && [ -d "${MY_VENV:-/nonexistent/dir}" ]
-    then
-        rm -r "$MY_VENV"
-    fi
-}
-
-
-trap clean_up EXIT
-set_up
-
-
 # Check that all source code is ASCII.
 #
-# I'd love to have rich Unicode, but I can live without it.  But we don't want
-# any surprises in contributions.
+# I'd love to have rich Unicode, but I can live without it.  Mainly we don't
+# want any surprises in contributions.
+#
+# TODO: Probably time to rewrite this in python.
 check_ascii() {
     local exotics
     exotics="$(
@@ -91,17 +65,24 @@ count_includes() {
 
 
 # Check that any includes of $1-pre.hxx are matched by $1-post.hxx ones.
+# TODO: Probably time to rewrite this in python.
 match_pre_post_headers() {
-    local NAME TEMPDIR PRE POST
+    local NAME PRE POST
     NAME="$1"
-    TEMPDIR="$MY_VENV/tmp-lint"
-    mkdir -p  "$TEMPDIR"
+    TEMPDIR="$(mktemp -d)"
+
+    # In case we get interrupted before we can clean up $TEMPDIR ourselves.
+    # (Next invocation will overwrite the trap.)
+    trap 'rm -rf -- "$TEMPDIR"'  EXIT
+
     PRE="$TEMPDIR/pre"
     POST="$TEMPDIR/post"
     count_includes "$SRCDIR/$NAME-pre.hxx" >"$PRE"
     count_includes "$SRCDIR/$NAME-post.hxx" >"$POST"
     DIFF="$(diff "$PRE" "$POST")" || true
-    rm -r -- "$TEMPDIR"
+
+    rm -rf -- "$TEMPDIR"
+
     if test -n "$DIFF"
     then
         cat <<EOF >&2
@@ -125,7 +106,6 @@ check_compiler_internal_headers() {
 cpplint() {
     local dialect includes
 
-    pip install -q clang-tidy
     if [ -e compile_commands.json ]
     then
         # This wrapper script runs in parallel, making it run faster on most
@@ -139,7 +119,7 @@ cpplint() {
         # overtakes the original tool, but using five times as much CPU.
         # At -j8 it actually seems to run faster than at -j16, and still with
         # "only" five times the original CPU time used.
-        run-clang-tidy -q -j8
+        uv run --with=clang-tidy run-clang-tidy -q -j8
     elif [ -e compile_flags ]
     then
         # The configure-based build writes its compiler options into this
@@ -171,7 +151,9 @@ EOF
     fi
 
     # Run Facebook's "infer" static analyser, if available.
-    # A "pip install" didn't work for me: No module named 'nltk'.
+    # A "pip install" didn't work for me: No module named 'nltk'.  Even if
+    # nltk was installed.
+    #
     # Instructions here: https://fbinfer.com/docs/getting-started/
     if which infer >/dev/null
     then
@@ -185,26 +167,18 @@ EOF
 
 
 pylint() {
-    pyflakes "$SRCDIR"/tools/*.py
-    ruff check -q "$SRCDIR"/tools/*.py
+    uv run --with=pyflakes pyflakes "$SRCDIR"/tools/*.py
+    uv run --with=ruff ruff check -q "$SRCDIR"/tools/*.py
 }
 
 
 shelllint() {
     local TLS="deprecations extract_version format lint todo update-copyright"
-    shellcheck "$SRCDIR/autogen.sh"
+    uv run --with=shellcheck.py shellcheck "$SRCDIR/autogen.sh"
     for s in $TLS
     do
-        shellcheck "$SRCDIR/tools/$s"
+        uv run --with=shellcheck.py shellcheck "$SRCDIR/tools/$s"
     done
-}
-
-
-mdlint() {
-    if which mdl >/dev/null
-    then
-        find . -name \*.md -exec mdl -c .markdownlint.yaml '{}' ';'
-    fi
 }
 
 
@@ -239,7 +213,6 @@ EOF
     shelllint
     check_news_version
     check_compiler_internal_headers
-    mdlint
     if [ $full == "yes" ]
     then
         cpplint
