Reformat `tools/lint`.

diff --git a/tools/lint b/tools/lint
--- a/tools/lint
+++ b/tools/lint
@@ -16,55 +16,55 @@ PQXXVERSION="$($SRCDIR/tools/extract_version)"
 
 # This version must be at the top of the NEWS file.
 check_news_version() {
-	if ! head -n1 $srcdir/NEWS | grep -q "^$PQXXVERSION\$"
-	then
-		cat <<EOF >&2
+    if ! head -n1 $srcdir/NEWS | grep -q "^$PQXXVERSION\$"
+    then
+        cat <<EOF >&2
 Version $PQXXVERSION is not at the top of NEWS.
 EOF
-		exit 1
-	fi
+        exit 1
+    fi
 }
 
 
 # Count number of times header $1 is included from each of given input files.
 # Output is lines of <filename>:<count>, one line per file, sorted.
 count_includes() {
-	local HEADER_NAME WS PAT
-	HEADER_NAME="$1"
-	shift
-	WS="[[:space:]]*"
-	PAT="^${WS}#${WS}include${WS}[<\"]$HEADER_NAME[>\"]"
-	grep -c "$PAT" $* | sort
+    local HEADER_NAME WS PAT
+    HEADER_NAME="$1"
+    shift
+    WS="[[:space:]]*"
+    PAT="^${WS}#${WS}include${WS}[<\"]$HEADER_NAME[>\"]"
+    grep -c "$PAT" $* | sort
 }
 
 
 # Any file that includes compiler-internal-pre.hxx must also include
 # compiler-internal-post.hxx, and vice versa.
 check_compiler_internal_headers() {
-	local TEMPDIR PRE POST HEADERS
-	TEMPDIR="$(mktemp -d)"
-	if test -z "$TEMPDIR"
-	then
-		echo >&2 "Could not create temporary directory."
-                exit 1
-	fi
-	PRE="$TEMPDIR/pre"
-	POST="$TEMPDIR/post"
-	HEADERS=$(find include/pqxx/* -type f | grep -v '\.swp$')
-	count_includes $SRCDIR/pqxx/internal/compiler-internal-pre.hxx $HEADERS >"$PRE"
-	count_includes $SRCDIR/pqxx/internal/compiler-internal-post.hxx $HEADERS >"$POST"
-	DIFF="$(diff "$PRE" "$POST")" || /bin/true
-	rm -r -- "$TEMPDIR"
-	if test -n "$DIFF"
-	then
-		cat <<EOF >&2
+    local TEMPDIR PRE POST HEADERS
+    TEMPDIR="$(mktemp -d)"
+    if test -z "$TEMPDIR"
+    then
+        echo >&2 "Could not create temporary directory."
+        exit 1
+    fi
+    PRE="$TEMPDIR/pre"
+    POST="$TEMPDIR/post"
+    HEADERS=$(find include/pqxx/* -type f | grep -v '\.swp$')
+    count_includes $SRCDIR/pqxx/internal/compiler-internal-pre.hxx $HEADERS >"$PRE"
+    count_includes $SRCDIR/pqxx/internal/compiler-internal-post.hxx $HEADERS >"$POST"
+    DIFF="$(diff "$PRE" "$POST")" || /bin/true
+    rm -r -- "$TEMPDIR"
+    if test -n "$DIFF"
+    then
+        cat <<EOF >&2
 The number of inclusions of compiler-internal.post.hxx does not match the number
 of inclusions of compiler-internal.pre.hxx:
 
 $DIFF
 EOF
-		exit 1
-	fi
+        exit 1
+    fi
 }
 
 
@@ -86,19 +86,20 @@ cpplint() {
 
 
 pylint() {
-	local PYFILES="$SRCDIR/tools/*.py $SRCDIR/tools/splitconfig"
-        echo "Skipping pocketlint; it's not up to date with Python3."
-	# if which pocketlint >/dev/null
-	# then
-	# 	pocketlint $PYFILES
-	# fi
+    local PYFILES="$SRCDIR/tools/*.py $SRCDIR/tools/splitconfig"
+    echo "Skipping pocketlint; it's not up to date with Python3."
+    # if which pocketlint >/dev/null
+    # then
+    # 	pocketlint $PYFILES
+    # fi
 
-        echo "Skipping flake8; it's not up to date with Python3."
-	# if which flake8 >/dev/null
-	# then
-	# 	flake8 $PYFILES
-	# fi
+    echo "Skipping flake8; it's not up to date with Python3."
+    # if which flake8 >/dev/null
+    # then
+    # 	flake8 $PYFILES
+    # fi
 }
+
 
 cpplint
 pylint
